### PR TITLE
[FIXED JENKINS-34676] - Do not interrupt the resolution loop if the module has been already loaded

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/JENKINS-34676

@reviewbybees @tfennelly @kzantow

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
FYI @daniel-beck In my case Jenkins uses the version without this patch: https://github.com/jenkinsci/js-modules/commit/dd98ceefcc28861b11272214aeb9bc32a3aaae62 . I'm not sure why...

**Comment by michaelneale** [comment]
ping @tfennelly - this one has been around for a while?

**Comment by oleg-nenashev** [comment]
@michaelneale from What I see the issue has been resolved . So feel free to close

**Comment by oleg-nenashev** [comment]
Closing since there is no response from the maintainer

**Pull request closed without merging**
